[WIP] update of yq command to v4
integr8ly/integreatly-operator pull request #1990
Opened 2021-07-21 10:54 UTC by Patryk-Stefanski

# Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist
- [ ] This change requires a documentation update 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added a test case that will be used to verify my changes 
- [ ] Verified independently on a cluster by reviewer

2021-07-29 13:23 UTC, austincunningham requested changes

2021-07-29 13:23 UTC, austincunningham commented on Makefile
> +	yq e -i '.metyqadata.annotations.in_prow="IN_PROW"' config/samples/integreatly-rhmi-cr.yml
looks like a typo here
```suggestion
	yq e -i '.metaadata.annotations.in_prow="IN_PROW"' config/samples/integreatly-rhmi-cr.yml
```

2021-07-29 13:26 UTC, austincunningham commented on Makefile
> +	yq e -i '.metyqadata.annotations.in_prow="IN_PROW"' config/samples/integreatly-rhmi-cr.yml
typo my own suggestion :facepalm:

2021-07-30 09:12 UTC, Patryk-Stefanski commented on Makefile
> +	yq e -i '.metyqadata.annotations.in_prow="IN_PROW"' config/samples/integreatly-rhmi-cr.yml
Typo is fixed.

2021-08-03 13:02 UTC, makslion commented
Verified that mentioned in this PR commands are succeeding while run with yq v4.9.8 installed. Also, randomly picked several changed commands and they were valid. Looks good. You can treat this as `LGTM`, but I want to have one extra sanity check

2021-08-24 11:01 UTC, KevFan commented
/ok-to-test

2021-08-24 14:47 UTC, Boomatang commented
adding the lgtm on behalf of @makslion 

/lgtm

2021-08-24 14:53 UTC, sergioifg94 commented
/approve

2021-08-24 14:55 UTC, makslion commented
@austincunningham thanks

2021-08-24 15:06 UTC, merged