[WIP] MGDAPI-4618 - address all linter issues with golangci-lint
integr8ly/integreatly-operator pull request #3243
Opened 2023-05-26 14:02 UTC by kramaranya

# Issue link

# What

# Verification steps

2023-05-29 11:12 UTC, Boomatang commented
/test multitenant-rhoam-e2e

2023-06-01 09:47 UTC, Boomatang requested changes
Couple of small points.

2023-06-01 13:14 UTC, kramaranya commented on pkg/products/threescale/reconciler_test.go
> +							list = &routev1.RouteList{ // nolint
Updated

2023-06-01 14:14 UTC, Fiona-Waters commented
Followed verification steps and can confirm that there were no errors in the output. Code changes look good. Will leave it to  @Boomatang to lgtm if he is happy with newest changes.

2023-06-01 14:24 UTC, Boomatang approved these changes
Changes look good to me
/lgtm

2023-06-01 14:56 UTC, KevFan commented
/approve

2023-06-01 15:03 UTC, merged